---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/users/{user_id}/posts/{post_id}/comments":
    parameters:
    - name: user_id
      in: path
      description: user_id from the path
      required: true
      schema:
        type: string
    - name: post_id
      in: path
      description: post_id from the path
      required: true
      schema:
        type: string
    get:
      summary: lists all comments of the selected post
      responses:
        '200':
          description: successful
  "/api/users/{user_id}/posts":
    parameters:
    - name: user_id
      in: path
      description: user_id from the path
      required: true
      schema:
        type: string
    get:
      summary: list all posts of selected user
      responses:
        '200':
          description: successful
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
